<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>

<body>

</body>

</html>

<script src="http://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>

<script>
    let p = new Promise(function (res, rej) {
        // setTimeout(() => {
        //     console.log(666)
        // }, 2000);

        // $.ajax({
        //     url:'./data.json',
        //     success:function(data){
        //         res(data)
        //     },
        //     error:function(err){
        //         erj(err)
        //     }
        // })

        res(111)
    }).then(function (data) {
        console.log(1)
    }, function (error) {
        console.log(0)
    }).catch((err) => {
        console.log(666, err)
    }).finally(() => {
        //不管是成功还是失败 都要执行的代码 我们可以放到这个函数中

    })
    // then  catch  finally   这三个方法都在promise的原型上
    // all  race  resolve  reject  

    var p1 = new Promise(function (res, rej) {
        setTimeout(() => {
            res(111)
        }, 2000);
    })
    var p2 = new Promise(function (res, rej) {
        setTimeout(() => {
            res(222)
        }, 3000);
    })
    var p3 = new Promise(function (res, rej) {
        setTimeout(() => {
            rej(333)
        }, 4000);
    })

    //所有都成功，才会走成功的回调函数   只要有一个失败，就会走对应的失败函数
    //executor函数是一个同步执行的函数，then catch 里边的函数是异步执行的 
    Promise.all([p1,p2,p3]).then((data)=>{
        console.log('data', data)
    },(err)=>{
        console.log('err', err)
    })

    Promise.allSettled([p1,p2,p3]).then((data)=>{
        console.log('data', data)
    })


    Promise.race([p1,p2,p3]).then((data)=>{
        console.log('success',data)
    },(err)=>{
        console.log('fail',err)
    })


    Promise.resolve(333333).then((data)=>{
        console.log(data)
    })


</script>